### ISSUE TITLE
REAL TIME INVESTIGATION ABOUT THE HACK : IS IT FINALLY FIXED ?!

### ISSUE THREAD

**Issue by TheSatanicAngeI** [zbot473/SurvivHacks#137]
This is the only feature I want to be implemented. 

I really like the colors you guys added I feel like playing paintball now :rofl: 

But seriously @zbot473 (:heart:) I understand that you and other people that contribute wants their way for the cheat to work but it would be really nice to replace shift with actual enabling aiming which mean if you press shift once you get into RMB to aim manually and if you re-click it it get back to RMB to switch or something.

I really like to aim manually as it look less obvious for hacking and make me loot in peace.

**Thanks for the amazing work btw**

PS : Squad is still broken tho

**Comment by IME9** [comment]
PS : Sometimes game freeze completely but no errors shows I think its because of ping thingy not sure

**Comment by IME9** [comment]
"[Violation] 'requestAnimationFrame' handler took 61ms"

And after that I was stuck in reload loop cuz game freeze :thinking:

**Comment by IME9** [comment]
Yep the freezing issue seems to be directly linked to RequestAnimationFrame()

**Comment by IME9** [comment]
Is it possible that the devs set the delay time for punching limited to the actual speed and with the hack having no such limits make it break frames or something and somehow that generate a fatal error ?

**Comment by BopItFreak** [comment]
can we fix auto loot

**Comment by IME9** [comment]
`[Violation] 'setTimeout' handler took 525ms`

Maybe its because of the extension added that it freeze...

chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/
:thinking:  


wait nvm it seems to have something to do with the scope.

I think we can't have a personalize scope anymore.  Cuz I just did a game without setting zoom stuff like not changing zoom at all and I think I was on the original scope and I didn't freeze I even won the game.

![Uploading wtf.PNG…]()

**Comment by IME9** [comment]
Nope did another game without the change scope and still froze weird....

**Comment by IME9** [comment]
Maybe you can't have more than 60fps :thinking:

**Comment by IME9** [comment]
>  the problem is likely being caused by a change in Surviv.io's code that cuts the websocket.

**Comment by killercloudj** [comment]
![surviv io 2d battle royale game](https://user-images.githubusercontent.com/38992642/49673250-da764a80-fa3b-11e8-81f3-9da1af383760.png)

**Comment by IME9** [comment]
https://github.com/Kalaborative/survivio-plus/commit/039de5a8661f41b349e04d2844c66d8c61a7c753

Kalaborative managed to get a fix for the new update that was working for solo/duos untill wood event or something even if it happened around the same time this lead me to conclude that the devs did made changes in the code other than adding new stuff for map etc.

**Comment by BopItFreak** [comment]
@IME9 Kalaborative's thing still freezes, but not as often

**Comment by IME9** [comment]
@BopItFreak  I can't use it at all because of net lag and the fact the thing is deprecated on chrome

**Comment by BopItFreak** [comment]
I think this is the end of surviv hacks

**Comment by BopItFreak** [comment]
ok so i turned off all modules, and it still freezes. Maybe something else?

**Comment by IME9** [comment]
**yeah, I'm pretty sure it has to do with background.js - there's some code in the source closing the websocket**

**Comment by BopItFreak** [comment]
better fix it

>

**Comment by zbot473** [comment]
@PowerOfUniverse you had something to fix it, no?

**Comment by RuanTM** [comment]
ok

**Comment by Dark-ness** [comment]
I also noted something interesting. I loaded one window with the extension and the other without the extension. I added them both to a duos game and when the hacked one froze, I could still move, except my screen (on the hacked one) wasn't updating. The other screen showed me moving in response to my button pushes, even though the hacked screen didn't. This leads me to believe that it is a visual issue because I was still in the game and moving, though I couldn't see anything changing, except on the vanilla one.

**Comment by IME9** [comment]
woah

**Comment by IME9** [comment]
@Dark-ness  That would make sense of why it happen randomly but it still doesn't explain why such glitch/bug occur nor why after a min it doesn't occur either. 

Its either right at the beginning or after 30 seconds but a higher delay and it doesn't occur anymore.

**Comment by IME9** [comment]
Going throught smoke freeze the game aswell.

**Comment by IME9** [comment]
It also only seems to occur while reloading or taking time-based item such as DRUGS or SODA. 

weird

**Comment by IME9** [comment]
**It seems that the visiual glitch IS caused by requesting a higher frame rate than possible. If you try to walk around while holding LMB to punch you'll have 99% of freezing like legit I've been able to do 6 matches in a row without a single freeze because I was taking my time to loot it doesn't seems to affect with guns that can spam.**

**Comment by Dark-ness** [comment]
Yeah that would make sense! I've managed to play a few matches by just playing slow, but I didn't realize that was what I was doing different. Thanks!

**Comment by IME9** [comment]
But it could also be linked to some variables being broken or that didn't syntax correctly in the new update.

If it was a visual glitch about the game even without hack it would occur while this happen with an extension.

So something is wrong with the script. 

Or the devs did made change in the web socket thingy or idk how that works.

Still the freezes happen randomly you just decrease your chances by not picking a scope underground and not doing many things at the same time give your game a good 30 seconds of slow looting or walking around and it doesn't seems to freeze afterwards.

**Comment by IME9** [comment]
But seriously I have no idea :disappointed:  if only I knew more about coding languages and stuff I would probably be able to understand stuff in the code itself. 

All I can do is make assumptions even if we notice circumstances in which the freezing bug occur it doesn't tell us **why**

**Comment by IME9** [comment]
> I also noted something interesting. I loaded one window with the extension and the other without the extension. I added them both to a duos game and when the hacked one froze, I could still move, except my screen (on the hacked one) wasn't updating. The other screen showed me moving in response to my button pushes, even though the hacked screen didn't. This leads me to believe that it is a visual issue because I was still in the game and moving, though I couldn't see anything changing, except on the vanilla one.

This just prove that the extension as an issue causing visual glitch

**Comment by alexvornoffice** [comment]
yeah I think the same something with variables, even if you knew programming JS language - the code is ugly and is hard to experiment... need new code to be clean so you can easily test things... the code is obfuscated need to be deobfuscated.

**Comment by IME9** [comment]
Well I mean this hack used to be the most popular and clean one.

I actually lag more without this hack.

Also Kalaborative one use another language that is deprecated to the end-user and even net lag taken in account is horrible making me play between 5-20 fps which is not stable at all. 

While I have a 75hrz and gtx 650

(ok just ignore my pentium dual core processor this pc is old af)

**Comment by IME9** [comment]
`[Violation] 'requestAnimationFrame' handler took 56ms`


I had console open at this exact moment when I took a soda this message appeared and I froze.

**Comment by WotDefek** [comment]
All I'm going to say is good luck fixing it :p

**Comment by danzam284** [comment]
The best way I found to reduce freezing and crashing was:
- Right when the game starts click z to turn the hack off temporarily
- Hide in somewhere like a bush or a table
- Wait about 30 seconds
- Play normally with hack
So far it worked 5/6 times for me. The one time that it did not work, I crashed while I was hiding in the bush so I did not lose any progress.

**Comment by BopItFreak** [comment]
I'm pretty sure this is an error in the code, not with the websocket and the devs. I've made bots with ws before, so yeah.

**Comment by IME9** [comment]
possible I'm currently testing the new update by @zbot473

**Comment by IME9** [comment]
https://github.com/zbot473/SurvivHacks/commit/e0e2b15d52c05f9a291067382fd23fc1b3fd7df1

Seems like the variables were outdated.

**Comment by IME9** [comment]
@zbot473  Sadly I knew about that but not quite I knew Kalaborative was able to update but it didn't fix the freezing on any game mode for his extension while your seems to work now not sure at 100% I did one game trying to mess around as much as I can and I never froze.

**Comment by IME9** [comment]
### Seems like the game still froze if taken a soda or drug early in the game looks like it make a loop message in console >r

**Comment by BopItFreak** [comment]
OK THIS HAS TO BE FIXED NOW! I am getting angry.

**Comment by BopItFreak** [comment]
![image](https://user-images.githubusercontent.com/41522720/49690478-afedc580-faff-11e8-9db4-b1bb97c5f9da.png)

**Comment by YESS808** [comment]
You're getting angry? You're demanding it gets "FIXED NOW!" ... seriously bro, be thankful for the work that has been put into it, don't demand someone to put more work into it for YOU.

**Comment by zbot473** [comment]
@YESS808 thanks man

**Comment by zbot473** [comment]
I am updating the freezefix branch with possible fixes
but they may not work

**Comment by Reeyaad** [comment]
It was working for some time, but now if you just open the game with the extension, and even disable everything and do nothing just hide somewhere it still freezes after around 1/2 minutes.

**Comment by Reeyaad** [comment]
but thanks anyway , it was a lot of fun to use it

**Comment by zbot473** [comment]
It is known. In the discord, we are trying to fix it.

**Comment by RuanTM** [comment]
thanks

**Comment by TheSatanicAngeI** [comment]
I'm trying to help too but I have no knowledge into this yet.
The most realistic assumptions are that its either

1. A visual glitch/bug

2. Surviv server closing the websocket when it detect suspicious activity. 

3. Error in the code.

**Comment by charlie45** [comment]
@zbot473 now is working bro thanks for everything 👍

**Comment by charlie45** [comment]
you don't have to do any of above i'm just download the freezefix branch and played the game and done!

**Comment by TheSatanicAngeI** [comment]
@charlie45  Wait the freeze fix has been fixed again or do only transparency set to 1 on freeze fix ; fix the freeze ?

**Comment by zbot473** [comment]
cool.

**Comment by charlie45** [comment]
@TheSatanicAngeI  I did nothing and freeze was fixed

**Comment by charlie45** [comment]
I didn't do any of the above solutions. 👍

**Comment by zbot473** [comment]
@charlie45 me too.
